import type {IRule} from "@/domain/iRule.ts";

const defaultRoute: IRule[] = [
    {
        rule_id: 1,
        parent_id: 0,
        type: 'menu',
        name: '仪表盘',
        path: '/dashboard',
        key: "dashboard",
        icon: "HeatMapOutlined",
    },
    {
        rule_id: 2,
        parent_id: 1,
        type: 'route',
        index: false,
        name: '仪表盘',
        icon: "PieChartOutlined",
        key: 'dashboard.analysis',
        path: '/dashboard/analysis',
        elementPath: '/dashboard/analysis',
    },
    {
        rule_id: 3,
        parent_id: 1,
        type: 'route',
        index: true,
        name: '分析页',
        icon: "BarChartOutlined",
        key: 'dashboard.monitor',
        path: '/dashboard/monitor',
        elementPath: '/dashboard/monitor',
    },
    {
        rule_id: 4,
        parent_id: 1,
        type: 'route',
        index: false,
        name: '工作台',
        icon: "LineChartOutlined",
        key: 'dashboard.workplace',
        path: '/dashboard/workplace',
        elementPath: '/dashboard/workplace',
    },
    {
        rule_id: 5,
        parent_id: 0,
        type: 'menu',
        name: '结果页',
        path: '/result',
        key: "result",
        icon: "AppstoreOutlined",
    },
    {
        rule_id: 6,
        parent_id: 5,
        type: 'route',
        index: true,
        name: '成功页',
        icon: "CheckCircleOutlined",
        key: 'result.success',
        path: '/result/success',
        elementPath: '/result/success',
    },
    {
        rule_id: 7,
        parent_id: 5,
        type: 'route',
        index: false,
        name: '失败页',
        icon: "CloseCircleOutlined",
        key: 'result.fail',
        path: '/result/fail',
        elementPath: '/result/fail',
    },
    {
        rule_id: 8,
        parent_id: 5,
        type: 'route',
        index: false,
        name: '警告页',
        icon: "WarningOutlined",
        key: 'result.warning',
        path: '/result/warning',
        elementPath: '/result/warning',
    },
    {
        rule_id: 9,
        parent_id: 5,
        type: 'route',
        index: false,
        name: '信息页',
        icon: "ExclamationCircleOutlined",
        key: 'result.info',
        path: '/result/info',
        elementPath: '/result/info',
    },
    {
        rule_id: 10,
        parent_id: 5,
        type: 'route',
        index: false,
        name: '403',
        icon: "AppstoreOutlined",
        key: 'result.403',
        path: '/result/403',
        elementPath: '/result/403',
    },
    {
        rule_id: 11,
        parent_id: 5,
        type: 'route',
        index: false,
        name: '404',
        icon: "AppstoreOutlined",
        key: 'result.404',
        path: '/result/404',
        elementPath: '/result/404',
    },
    {
        rule_id: 12,
        parent_id: 5,
        type: 'route',
        index: false,
        name: '500',
        icon: "AppstoreOutlined",
        key: 'result.500',
        path: '/result/500',
        elementPath: '/result/500',
    },
    {
        rule_id: 13,
        parent_id: 0,
        type: 'menu',
        index: false,
        name: '权限管理',
        icon: "SafetyCertificateOutlined",
        key: 'auth',
        path: '/auth',
        elementPath: null,
    },
    {
        rule_id: 14,
        parent_id: 13,
        type: 'route',
        index: true,
        name: '页面权限',
        icon: "AppstoreOutlined",
        key: 'auth.page',
        path: '/auth/page',
        elementPath: '/auth/page',
    },
    {
        rule_id: 15,
        parent_id: 13,
        type: 'route',
        index: true,
        name: '按钮权限',
        icon: "AppstoreOutlined",
        key: 'auth.button',
        path: '/auth/button',
        elementPath: '/auth/button',
    },
    {
        rule_id: 16,
        parent_id: 15,
        type: 'rule',
        name: '新增权限',
        key: 'auth.button.create',
    },
    {
        rule_id: 17,
        parent_id: 15,
        type: 'rule',
        name: '编辑权限',
        key: 'auth.button.update',
    },
    {
        rule_id: 18,
        parent_id: 15,
        type: 'rule',
        name: '删除权限',
        key: 'auth.button.delete',
    },
    {
        rule_id: 19,
        parent_id: 15,
        type: 'rule',
        name: '新增权限',
        key: 'auth.button.query',
    },
]

export default defaultRoute
