import type {IRule} from "@/domain/iRule.ts";

const defaultRoute: IRule[] = [
    {
        rule_id: 1,
        parent_id: 0,
        type: 'menu',
        name: '仪表盘',
        path: '/dashboard',
        key: "dashboard",
        icon: "HeatMapOutlined",
    },
    {
        rule_id: 2,
        parent_id: 1,
        type: 'route',
        index: true,
        name: '分析页',
        icon: "BarChartOutlined",
        key: 'dashboard.index',
        path: '/dashboard/index',
        elementPath: '/dashboard/index',
    },
    {
        rule_id: 3,
        parent_id: 1,
        type: 'route',
        index: false,
        name: '仪表盘',
        icon: "PieChartOutlined",
        key: 'dashboard.analysis',
        path: '/dashboard/analysis',
        elementPath: '/dashboard/analysis',
    },
    {
        rule_id: 4,
        parent_id: 1,
        type: 'route',
        index: false,
        name: '工作台',
        icon: "LineChartOutlined",
        key: 'dashboard.monitor',
        path: '/dashboard/monitor',
        elementPath: '/dashboard/monitor',
    },
    {
        rule_id: 5,
        parent_id: 0,
        type: 'menu',
        name: '结果页',
        path: '/result',
        key: "result",
        icon: "AppstoreOutlined",
    },
    {
        rule_id: 6,
        parent_id: 5,
        type: 'route',
        index: true,
        name: '成功页',
        icon: "CheckCircleOutlined",
        key: 'result.success',
        path: '/result/success',
        elementPath: '/result/success',
    },
    {
        rule_id: 7,
        parent_id: 5,
        type: 'route',
        index: false,
        name: '失败页',
        icon: "CloseCircleOutlined",
        key: 'result.fail',
        path: '/result/fail',
        elementPath: '/result/fail',
    },
    {
        rule_id: 8,
        parent_id: 5,
        type: 'route',
        index: false,
        name: '警告页',
        icon: "WarningOutlined",
        key: 'result.warning',
        path: '/result/warning',
        elementPath: '/result/warning',
    },
    {
        rule_id: 9,
        parent_id: 5,
        type: 'route',
        index: false,
        name: '信息页',
        icon: "ExclamationCircleOutlined",
        key: 'result.info',
        path: '/result/info',
        elementPath: '/result/info',
    },
    {
        rule_id: 10,
        parent_id: 0,
        type: 'route',
        index: true,
        name: '首页',
        icon: "HomeOutlined",
        key: 'index',
        path: '/index',
        elementPath: '/index',
    }
]

export default defaultRoute
