import type {IRule} from "@/domain/iRule.ts";

const defaultRoute: IRule[] = [
    {
        rule_id: 1,
        parent_id: 0,
        type: 'menu',
        name: '仪表盘',
        local: "menu.dashboard",
        path: '/dashboard',
        key: "dashboard",
        icon: "HeatMapOutlined",
    },
    {
        rule_id: 2,
        parent_id: 1,
        type: 'route',
        index: false,
        name: '分析页',
        local: "menu.analysis",
        icon: "PieChartOutlined",
        key: 'dashboard.analysis',
        path: '/dashboard/analysis',
        elementPath: '/dashboard/analysis',
    },
    {
        rule_id: 3,
        parent_id: 1,
        type: 'route',
        index: true,
        name: '监控页',
        local: "menu.monitor",
        icon: "BarChartOutlined",
        key: 'dashboard.monitor',
        path: '/dashboard/monitor',
        elementPath: '/dashboard/monitor',
    },
    {
        rule_id: 4,
        parent_id: 1,
        type: 'route',
        index: false,
        name: '工作台',
        local: "menu.workplace",
        icon: "LineChartOutlined",
        key: 'dashboard.workplace',
        path: '/dashboard/workplace',
        elementPath: '/dashboard/workplace',
    },
    {
        rule_id: 5,
        parent_id: 0,
        type: 'menu',
        name: '结果页',
        local: "menu.result",
        path: '/result',
        key: "result",
        icon: "AppstoreOutlined",
    },
    {
        rule_id: 6,
        parent_id: 5,
        type: 'route',
        index: true,
        name: '成功页',
        local: "menu.result.success",
        icon: "CheckCircleOutlined",
        key: 'result.success',
        path: '/result/success',
        elementPath: '/result/success',
    },
    {
        rule_id: 7,
        parent_id: 5,
        type: 'route',
        index: false,
        name: '失败页',
        local: "menu.result.fail",
        icon: "CloseCircleOutlined",
        key: 'result.fail',
        path: '/result/fail',
        elementPath: '/result/fail',
    },
    {
        rule_id: 8,
        parent_id: 5,
        type: 'route',
        index: false,
        name: '警告页',
        local: "menu.result.warning",
        icon: "WarningOutlined",
        key: 'result.warning',
        path: '/result/warning',
        elementPath: '/result/warning',
    },
    {
        rule_id: 9,
        parent_id: 5,
        type: 'route',
        index: false,
        name: '信息页',
        local: "menu.result.info",
        icon: "ExclamationCircleOutlined",
        key: 'result.info',
        path: '/result/info',
        elementPath: '/result/info',
    },
    {
        rule_id: 10,
        parent_id: 5,
        type: 'route',
        index: false,
        name: '403',
        local: "menu.result.403",
        icon: "AppstoreOutlined",
        key: 'result.403',
        path: '/result/403',
        elementPath: '/result/403',
    },
    {
        rule_id: 11,
        parent_id: 5,
        type: 'route',
        index: false,
        name: '404',
        local: "menu.result.404",
        icon: "AppstoreOutlined",
        key: 'result.404',
        path: '/result/404',
        elementPath: '/result/404',
    },
    {
        rule_id: 12,
        parent_id: 5,
        type: 'route',
        index: false,
        name: '500',
        local: "menu.result.500",
        icon: "AppstoreOutlined",
        key: 'result.500',
        path: '/result/500',
        elementPath: '/result/500',
    },
    {
        rule_id: 13,
        parent_id: 0,
        type: 'menu',
        index: false,
        name: '权限管理',
        local: "menu.auth",
        icon: "SafetyCertificateOutlined",
        key: 'auth',
        path: '/auth',
        elementPath: null,
    },
    {
        rule_id: 14,
        parent_id: 13,
        type: 'route',
        index: true,
        name: '页面权限',
        local: "menu.auth.page",
        icon: "AppstoreOutlined",
        key: 'auth.page',
        path: '/auth/page',
        elementPath: '/auth/page',
    },
    {
        rule_id: 15,
        parent_id: 13,
        type: 'route',
        index: true,
        name: '按钮权限',
        local: "menu.auth.button",
        icon: "AppstoreOutlined",
        key: 'auth.button',
        path: '/auth/button',
        elementPath: '/auth/button',
    },
    {
        rule_id: 16,
        parent_id: 15,
        type: 'rule',
        name: '新增权限',
        key: 'auth.button.create',
    },
    {
        rule_id: 17,
        parent_id: 15,
        type: 'rule',
        name: '编辑权限',
        key: 'auth.button.update',
    },
    {
        rule_id: 18,
        parent_id: 15,
        type: 'rule',
        name: '删除权限',
        key: 'auth.button.delete',
    },
    {
        rule_id: 19,
        parent_id: 15,
        type: 'rule',
        name: '新增权限',
        key: 'auth.button.query',
    },
    {
        rule_id: 20,
        parent_id: 0,
        type: 'menu',
        name: '多级菜单',
        local: "menu.multi-menu",
        icon: "AppstoreOutlined",
        key: 'multi-menu',
        path: '/multi-menu',
    },
    {
        rule_id: 21,
        parent_id: 20,
        type: 'menu',
        index: false,
        name: '二级菜单',
        local: "menu.multi-menu.two",
        icon: "AppstoreOutlined",
        key: 'multi-menu.two',
        path: '/multi-menu/two',
    },
    {
        rule_id: 22,
        parent_id: 20,
        type: 'route',
        index: true,
        name: '二级页面',
        local: "menu.multi-menu.first",
        icon: "AppstoreOutlined",
        key: 'multi-menu.first',
        path: '/multi-menu/first',
        elementPath: '/multi-menu/first',
    },
    {
        rule_id: 23,
        parent_id: 21,
        type: 'menu',
        index: false,
        name: '三级菜单',
        local: "menu.multi-menu.two.three",
        icon: "AppstoreOutlined",
        key: 'multi-menu.two.three',
        path: '/multi-menu/two/three',
    },
    {
        rule_id: 24,
        parent_id: 21,
        type: 'route',
        index: true,
        name: '三级页面',
        local: "menu.multi-menu.two.second",
        icon: "AppstoreOutlined",
        key: 'multi-menu.two.second',
        path: '/multi-menu/two/second',
        elementPath: '/multi-menu/second',
    },
    {
        rule_id: 25,
        parent_id: 23,
        type: 'route',
        index: true,
        name: '四级页面',
        local: "menu.multi-menu.two.three.third",
        icon: "AppstoreOutlined",
        key: 'multi-menu.two.three.third',
        path: '/multi-menu/two/three/third',
        elementPath: '/multi-menu/third',
    },
]

export default defaultRoute
